server:
  port: 0

spring:
  application:
    name: warehouse
  datasource:
    driverClassName: org.postgresql.Driver
    username: warehouse
    password: warehouse
    url: jdbc:postgresql://localhost:6544/warehouse
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/