server:
  port: 8080

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.telemetry.collector: DEBUG
    org.springframework.kafka: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/