server:
  port: 0

spring:
  application:
    name: shopping-store
  datasource:
    driverClassName: org.postgresql.Driver
    username: store
    password: store
    url: jdbc:postgresql://localhost:6542/store
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/